# Generated by Django 5.0.4 on 2024-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('Postcode', models.CharField(max_length=8)),
                ('Password', models.CharField(max_length=50)),
                ('Policy_agreement', models.BooleanField()),
            ],
        ),
    ]
