# Generated by Django 5.0.4 on 2024-05-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
