# Generated by Django 5.0.4 on 2024-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Role',
            field=models.CharField(default='Employee', max_length=50),
        ),
    ]
