# Generated by Django 5.0.4 on 2024-05-16 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0008_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Join_Datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
