# Generated by Django 5.0.4 on 2024-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0011_alter_user_join_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Join_Datetime',
            field=models.DateTimeField(),
        ),
    ]
