# Generated by Django 5.0.4 on 2024-05-16 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0016_remove_user_join_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
