# Generated by Django 5.0.4 on 2024-05-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0017_user_joined_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Contract_Number', models.IntegerField()),
                ('Due_date', models.DateField()),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titlle', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Create_at', models.DateField(auto_now_add=True)),
                ('Status', models.BooleanField()),
                ('contract_manager', models.ManyToManyField(to='my_smartwork_app.manager')),
                ('employee', models.ManyToManyField(to='my_smartwork_app.employee')),
                ('customer', models.ManyToManyField(to='my_smartwork_app.customer')),
            ],
        ),
    ]
