# Generated by Django 5.0.4 on 2024-05-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0018_customer_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Create_at',
            new_name='Created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Create_at',
            new_name='Created_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Contract_Number',
            field=models.CharField(max_length=50),
        ),
    ]
