# Generated by Django 5.0.4 on 2024-05-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_smartwork_app', '0019_rename_create_at_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Status',
            new_name='Activate',
        ),
    ]
